import { existsSync, readFileSync } from "node:fs";

import { atomicWriteFile, proxyGatePath, runDockerCompose } from "./common.mjs";

/**
 * The reverse proxy's own, independent kill switch: a single nginx `set`
 * directive, atomically rewritten and bind-mounted read-only into the
 * reverse-proxy container (see infrastructure/docker/reverse-proxy). When
 * active, ingestion.conf's two exact RUM/logs locations return 410 before
 * ever calling proxy_pass — OpenObserve is never reached. Independent of,
 * and a stronger guarantee than, the browser-side control document: this
 * one cannot be bypassed by an already-loaded page that never re-polls.
 */
export function writeProxyGate(active) {
  const content = `# Generated by scripts/lab/proxy-gate.mjs — do not edit by hand.\nset $frontend_observability_kill_switch_active "${active ? "1" : "0"}";\n`;
  atomicWriteFile(proxyGatePath, content, { mode: 0o644 });
}

export function readProxyGateActive() {
  if (!existsSync(proxyGatePath)) return false;
  return /\$frontend_observability_kill_switch_active\s+"1"/.test(
    readFileSync(proxyGatePath, "utf8"),
  );
}

/**
 * `nginx -t` must pass before a reload is ever attempted, and the reload's
 * own result is verified afterward — an operator script that silently
 * leaves the proxy running a stale or broken config is worse than one that
 * fails loudly.
 */
export function reloadReverseProxy() {
  const test = runDockerCompose(["exec", "-T", "reverse-proxy", "nginx", "-t"], {
    capture: true,
    allowFailure: true,
  });
  if (test.status !== 0) {
    throw new Error(
      `nginx -t failed; refusing to reload reverse-proxy.\n${test.stdout ?? ""}\n${test.stderr ?? ""}`,
    );
  }

  const reload = runDockerCompose(["exec", "-T", "reverse-proxy", "nginx", "-s", "reload"], {
    capture: true,
    allowFailure: true,
  });
  if (reload.status !== 0) {
    throw new Error(`nginx -s reload failed.\n${reload.stdout ?? ""}\n${reload.stderr ?? ""}`);
  }

  const verify = runDockerCompose(["exec", "-T", "reverse-proxy", "nginx", "-t"], {
    capture: true,
    allowFailure: true,
  });
  if (verify.status !== 0) {
    throw new Error("reverse-proxy did not come back healthy (nginx -t) after reload.");
  }
}

/**
 * `nginx -s reload` triggers a graceful worker respawn: old workers finish
 * in-flight requests and new ones take over, which is not instantaneous. A
 * request issued in the same tick as reloadReverseProxy() returning can
 * occasionally race an old worker mid-shutdown (seen as a reset/hangup
 * rather than the new config's response). Callers that need to observe the
 * *post*-reload behavior immediately should await this afterward.
 */
export function waitForReloadSettle(ms = 500) {
  return new Promise((resolve) => setTimeout(resolve, ms));
}
