export const ReasonCodes = Object.freeze({
  NONE: "NONE",
  OPTIONS_INVALID: "OPTIONS_INVALID",
  UNSUPPORTED_RUNTIME: "UNSUPPORTED_RUNTIME",
  CONFIG_DISABLED: "CONFIG_DISABLED",
  CONFIG_UNAVAILABLE: "CONFIG_UNAVAILABLE",
  CONFIG_TIMEOUT: "CONFIG_TIMEOUT",
  CONFIG_TOO_LARGE: "CONFIG_TOO_LARGE",
  CONFIG_HTTP_ERROR: "CONFIG_HTTP_ERROR",
  CONFIG_CONTENT_TYPE_INVALID: "CONFIG_CONTENT_TYPE_INVALID",
  CONFIG_JSON_INVALID: "CONFIG_JSON_INVALID",
  CONFIG_SCHEMA_INVALID: "CONFIG_SCHEMA_INVALID",
  CONFIG_EXPIRED: "CONFIG_EXPIRED",
  CONFIG_NOT_YET_VALID: "CONFIG_NOT_YET_VALID",
  ADAPTER_UNAVAILABLE: "ADAPTER_UNAVAILABLE",
  ADAPTER_ERROR: "ADAPTER_ERROR",
  ADAPTER_INITIALIZATION_FAILED: "ADAPTER_INITIALIZATION_FAILED",
  INITIALIZATION_CONFLICT: "INITIALIZATION_CONFLICT",
  INVALID_CONSENT: "INVALID_CONSENT",
  CONSENT_NOT_GRANTED: "CONSENT_NOT_GRANTED",
  NOT_ACTIVE: "NOT_ACTIVE",
  INVALID_ACTION: "INVALID_ACTION",
  INVALID_ERROR: "INVALID_ERROR",
  SHUTDOWN: "SHUTDOWN",
  INTERNAL_ERROR: "INTERNAL_ERROR",
});

export function isReasonCode(value) {
  return Object.values(ReasonCodes).includes(value);
}
